other:
- Key: null
- Link: https://aihubmix.com/v1/chat/completions
spark:
- Spark_Link: https://spark-api-open.xf-yun.com/v1/chat/completions
- lite_Key: null
- generalv3_Key: null
- pro-128k_Key: null
- max-32_Key: null
- 4.0Ultra_Key: null
- generalv3.5_Key: null
